### ISSUE TITLE
关于攻击示例的讨论

### ISSUE THREAD

**Issue by FranzKafkaYu** [hahahrfool/xtls-#2]
首先声明一下，我本身并不懂网络协议，也没有阅读过xray源码。
从你的的攻击示例，主要就两点:1.使服务端陷入无限循环，这个看样子是可以的，但其实没有意义，真要消耗服务器资源DDOS更简单高效。另外，单个连接触发循环的消耗并不大，除非有上千个并发连接，但是这对攻击方的消耗也是巨大的，这样攻击不太具有现实意义   2.探测xtls，这个不太可能，从伪装https-> xray服务器端再到响应返回形成闭环，这中间网络状态，服务器状态(影响代码执行)都是不可控的变量，影响最后的时间统计，如何得出确定的模型关系?起码线性关系是不可能的。

**Comment by hldh214** [comment]
2 不是可以通过不同长度的循环配合响应时间做拟合吗

**Comment by FranzKafkaYu** [comment]
> 2 不是可以通过不同长度的循环配合响应时间做拟合吗

这个时间如何来测量?数据从攻击者的服务器发出，中间通过无线网络传输到xray服务器，最后到响应服务器，这中间网络状态，xray服务器的状态都是实时变化的，都会造成不可测量的误差，怎么会形成线性的时间关系?如果xray服务前置了一些Nginx等，又会引入新的差异。这个时间与循环长度绝不是简简单单的线性关系

**Comment by hldh214** [comment]
> > 2 不是可以通过不同长度的循环配合响应时间做拟合吗
> 
> 这个时间如何来测量?数据从攻击者的服务器发出，中间通过无线网络传输到xray服务器，最后到响应服务器，这中间网络状态，xray服务器的状态都是实时变化的，都会造成不可测量的误差，怎么会形成线性的时间关系?如果xray服务前置了一些Nginx等，又会引入新的差异。这个时间与循环长度绝不是简简单单的线性关系

因为我也没有上手做实测, 只是结合项目 readme 说说我的理解, op 认为构造特殊数据包能让 xtls 相关代码进入循环, 若此循环可以造成响应时间的增加, 则可通过构造不同次数的循环来结合响应时间来做拟合.

至于前置 Nginx 等等一系列其他因素跟主动探测无关, 因为无论前置什么服务都无法改变响应时间变长的既定事实.

**Comment by FranzKafkaYu** [comment]
> 

是的，响应时间是会变长，但这并不代表能精准识别xtls.因为你伪造的的数据长度变长，本身也会让xray服务处理的时间变长，再加上外部不可控的复杂性，你没法确定时间变长就是因为"使用了xtls”

**Comment by hldh214** [comment]
> > 
> 
> 是的，响应时间是会变长，但这并不代表能精准识别xtls.因为你伪造的的数据长度变长，本身也会让xray服务处理的时间变长，再加上外部不可控的复杂性，你没法确定时间变长就是因为"使用了xtls”

那如果再结合对比正常的服务的响应时间呢, 比如同样是逐次增加的循环次数, xtls 服务会逐次增大响应时间, 而普通服务则没有明显的响应时间的变化

**Comment by FranzKafkaYu** [comment]
> > > 
> > 
> > 
> > 是的，响应时间是会变长，但这并不代表能精准识别xtls.因为你伪造的的数据长度变长，本身也会让xray服务处理的时间变长，再加上外部不可控的复杂性，你没法确定时间变长就是因为"使用了xtls”
> 
> 那如果再结合对比正常的服务的响应时间呢, 比如同样是逐次增加的循环次数, xtls 服务会逐次增大响应时间, 而普通服务则没有明显的响应时间的变化

那你要保证你的对照服务器必须要跟你要攻击的xray服务器网络环境，系统环境尽可能保持一致(实际上这很难)，发送相同的伪造的数据。事实上机器同一台宿主机上虚拟出来的VPS(也可以用docker来制造这种环境)，这个响应时间绝对是会有差异的。总之，有太多不可控的因素了，要得出这个模型绝不是那么简单的事

**Comment by FranzKafkaYu** [comment]
> 

如果xray服务器针对特定数据的响应时间确实会呈现某种规律，确实可以用于探，但关键在于没有规律。假如你作为攻击方，向一个服务器发起所谓的233攻击，假如第一次只触发一次循环，响应时间为t1，第二次触发两次循环，响应时间为t2，第三次第四次以此类推，t1，t2……tn一定会存在某种关系吗，并不一定。从逻辑推理来讲，我不使用xtls的服务器，由于网络波动，服务器状态的变化，t1，t2…tn的时间也有可能会与有xtls的表现一致（所谓表现一致是指只知道响应时间变长）。从逻辑推理角度来看，响应时间变长与xray服务器使用xtls两者并不互为充分必要条件。在你没找到可以量化的规律之前，没有所谓的特定行为。

**Comment by hahahrfool** [comment]
> 如果xray服务器针对特定数据的响应时间确实会呈现某种规律，确实可以用于探，但关键在于没有规律。假如你作为攻击方，向一个服务器发起所谓的233攻击，假如第一次只触发一次循环，响应时间为t1，第二次触发两次循环，响应时间为t2，第三次第四次以此类推，t1，t2……tn一定会存在某种关系吗，并不一定。从逻辑推理来讲，我不使用xtls的服务器，由于网络波动，服务器状态的变化，t1，t2…tn的时间也有可能会与有xtls的表现一致（所谓表现一致是指只知道响应时间变长）。从逻辑推理角度来看，响应时间变长与xray服务器使用xtls两者并不互为充分必要条件。在你没找到可以量化的规律之前，没有所谓的特定行为。


首先，关于你说 “上千个并发连接，但是这对攻击方的消耗也是巨大的”， 这个不成立。上千个很简单啊，以golang举例，一个go func(){}() 套在一个 for循环里，循环一千次即可，很简单。假设每一个连接发送1kb，一共流量才消耗1MB，不知道你说的消耗在哪里。

第二，关于规律，随着流量的提高，规律会越来越显著。如果每次只发送 1、2、3次循环，当然很容易被网络波动影响。但是如果1次发送10循环，一次100循环，一次一千循环，一次一万循环呢？

你说的自然是有可能的，但是没有实测的话我们都没法说谁对谁错。我是肯定不测的，希望有谁有余力可以测测。

**Comment by hahahrfool** [comment]
我猜测，最快的情况，一百万次循环至少需要100ms，如果主机差的话搞不好要500ms。

查看如下循环代码：
```
package main
import "fmt"
import "time"
import "math/rand"

func main(){
    rand.Seed(time.Now().UTC().UnixNano())
    x1:=time.Now()
    j:=0
    for i:=0;i<1000000;i++{
        j+=2*rand.Intn(200)
    }   
    fmt.Println(j, time.Now() .Sub( x1))
}

```

在我的机子上耗时22ms；而 xtls里的判断显然比这个负载的多，100ms应该是正常的推断；

而且，关键不仅仅是这个循环，还有tls握手别忘了，那些握手都是真实的，如果我能发送一千个1k包，就会产生一千个tls握手，这些握手也要以100ms为单位来计算。墙完全可以先测出握手平均速度，然后再开始发探测包。

如此看来的话作为ddos攻击可能价值更大，因为不在乎网络波动，每1MB流量就可以让你服务器产生大概0.5-1秒的延迟，那么上传100MB流量只需要1分钟不到，就可以将你的服务器的cpu完全占满，过不了一会儿你的服务器就停止响应了

**Comment by FranzKafkaYu** [comment]
> > 如果xray服务器针对特定数据的响应时间确实会呈现某种规律，确实可以用于探，但关键在于没有规律。假如你作为攻击方，向一个服务器发起所谓的233攻击，假如第一次只触发一次循环，响应时间为t1，第二次触发两次循环，响应时间为t2，第三次第四次以此类推，t1，t2……tn一定会存在某种关系吗，并不一定。从逻辑推理来讲，我不使用xtls的服务器，由于网络波动，服务器状态的变化，t1，t2…tn的时间也有可能会与有xtls的表现一致（所谓表现一致是指只知道响应时间变长）。从逻辑推理角度来看，响应时间变长与xray服务器使用xtls两者并不互为充分必要条件。在你没找到可以量化的规律之前，没有所谓的特定行为。
> 
> 首先，关于你说 “上千个并发连接，但是这对攻击方的消耗也是巨大的”， 这个不成立。上千个很简单啊，以golang举例，一个go func(){}() 套在一个 for循环里，循环一千次即可，很简单。假设每一个连接发送1kb，一共流量才消耗1MB，不知道你说的消耗在哪里。
> 
> 第二，关于规律，随着流量的提高，规律会越来越显著。如果每次只发送 1、2、3次循环，当然很容易被网络波动影响。但是如果1次发送10循环，一次100循环，一次一千循环，一次一万循环呢？
> 
> 你说的自然是有可能的，但是没有实测的话我们都没法说谁对谁错。我是肯定不测的，希望有谁有余力可以测测。



> > 如果xray服务器针对特定数据的响应时间确实会呈现某种规律，确实可以用于探，但关键在于没有规律。假如你作为攻击方，向一个服务器发起所谓的233攻击，假如第一次只触发一次循环，响应时间为t1，第二次触发两次循环，响应时间为t2，第三次第四次以此类推，t1，t2……tn一定会存在某种关系吗，并不一定。从逻辑推理来讲，我不使用xtls的服务器，由于网络波动，服务器状态的变化，t1，t2…tn的时间也有可能会与有xtls的表现一致（所谓表现一致是指只知道响应时间变长）。从逻辑推理角度来看，响应时间变长与xray服务器使用xtls两者并不互为充分必要条件。在你没找到可以量化的规律之前，没有所谓的特定行为。
> 
> 首先，关于你说 “上千个并发连接，但是这对攻击方的消耗也是巨大的”， 这个不成立。上千个很简单啊，以golang举例，一个go func(){}() 套在一个 for循环里，循环一千次即可，很简单。假设每一个连接发送1kb，一共流量才消耗1MB，不知道你说的消耗在哪里。
> 
> 第二，关于规律，随着流量的提高，规律会越来越显著。如果每次只发送 1、2、3次循环，当然很容易被网络波动影响。但是如果1次发送10循环，一次100循环，一次一千循环，一次一万循环呢？
> 
> 你说的自然是有可能的，但是没有实测的话我们都没法说谁对谁错。我是肯定不测的，希望有谁有余力可以测测。

1.针对第一点:你自己也说了，要触发这个循环得由xray服务端通过write函数写入给客户端的数据。那么如果你要攻击xray服务器，首先要由客户端连接到xray服务器向你的攻击服务器本体请求数据，而且单个连接肯定无法形成有效攻击，起码得成千上万个客户端。通过同一台xray服务端像攻击服务器本体发起请求（并发)。其次，你所说的for循环并不算是真正的并发（这里我可能不太懂go语言的特性)，并发一定要是同一时刻同时执行多个任务，像你举例的for循环不该是一个任务执行后再循环执行下一个任务么?除非你的循环体内是创建线程/进程。第三，你所有的处理都只看到了简单的数据交换，但是CPU资源（包括线程资源、内存带宽等其他你都没有考虑进去），如果你觉得这个并发量不难（别忘了在你调用write函数写数据给客户端之前的其他工作，TLS的加解密等等），你大可以本地写一个C/S服务来测试一下对性能的损耗。
2.随着流量的提高，规律会越来越明显。这个明显具体是什么?不要笼统地说时间会变长，要有可计算的公式才叫规律。事实上由于外部环境的复杂性（网络环境，服务器环境等）要得出这个规律并不简单，甚至是不可能的。

**Comment by hahahrfool** [comment]
> > > 如果xray服务器针对特定数据的响应时间确实会呈现某种规律，确实可以用于探，但关键在于没有规律。假如你作为攻击方，向一个服务器发起所谓的233攻击，假如第一次只触发一次循环，响应时间为t1，第二次触发两次循环，响应时间为t2，第三次第四次以此类推，t1，t2……tn一定会存在某种关系吗，并不一定。从逻辑推理来讲，我不使用xtls的服务器，由于网络波动，服务器状态的变化，t1，t2…tn的时间也有可能会与有xtls的表现一致（所谓表现一致是指只知道响应时间变长）。从逻辑推理角度来看，响应时间变长与xray服务器使用xtls两者并不互为充分必要条件。在你没找到可以量化的规律之前，没有所谓的特定行为。
> > 
> > 
> > 首先，关于你说 “上千个并发连接，但是这对攻击方的消耗也是巨大的”， 这个不成立。上千个很简单啊，以golang举例，一个go func(){}() 套在一个 for循环里，循环一千次即可，很简单。假设每一个连接发送1kb，一共流量才消耗1MB，不知道你说的消耗在哪里。
> > 第二，关于规律，随着流量的提高，规律会越来越显著。如果每次只发送 1、2、3次循环，当然很容易被网络波动影响。但是如果1次发送10循环，一次100循环，一次一千循环，一次一万循环呢？
> > 你说的自然是有可能的，但是没有实测的话我们都没法说谁对谁错。我是肯定不测的，希望有谁有余力可以测测。
> 
> > > 如果xray服务器针对特定数据的响应时间确实会呈现某种规律，确实可以用于探，但关键在于没有规律。假如你作为攻击方，向一个服务器发起所谓的233攻击，假如第一次只触发一次循环，响应时间为t1，第二次触发两次循环，响应时间为t2，第三次第四次以此类推，t1，t2……tn一定会存在某种关系吗，并不一定。从逻辑推理来讲，我不使用xtls的服务器，由于网络波动，服务器状态的变化，t1，t2…tn的时间也有可能会与有xtls的表现一致（所谓表现一致是指只知道响应时间变长）。从逻辑推理角度来看，响应时间变长与xray服务器使用xtls两者并不互为充分必要条件。在你没找到可以量化的规律之前，没有所谓的特定行为。
> > 
> > 
> > 首先，关于你说 “上千个并发连接，但是这对攻击方的消耗也是巨大的”， 这个不成立。上千个很简单啊，以golang举例，一个go func(){}() 套在一个 for循环里，循环一千次即可，很简单。假设每一个连接发送1kb，一共流量才消耗1MB，不知道你说的消耗在哪里。
> > 第二，关于规律，随着流量的提高，规律会越来越显著。如果每次只发送 1、2、3次循环，当然很容易被网络波动影响。但是如果1次发送10循环，一次100循环，一次一千循环，一次一万循环呢？
> > 你说的自然是有可能的，但是没有实测的话我们都没法说谁对谁错。我是肯定不测的，希望有谁有余力可以测测。
> 
> 1.针对第一点:你自己也说了，要触发这个循环得由xray服务端通过write函数写入给客户端的数据。那么如果你要攻击xray服务器，首先要由客户端连接到xray服务器向你的攻击服务器本体请求数据，而且单个连接肯定无法形成有效攻击，起码得成千上万个客户端。通过同一台xray服务端像攻击服务器本体发起请求（并发)。其次，你所说的for循环并不算是真正的并发（这里我可能不太懂go语言的特性)，并发一定要是同一时刻同时执行多个任务，像你举例的for循环不该是一个任务执行后再循环执行下一个任务么?除非你的循环体内是创建线程/进程。第三，你所有的处理都只看到了简单的数据交换，但是CPU资源（包括线程资源、内存带宽等其他你都没有考虑进去），如果你觉得这个并发量不难（别忘了在你调用write函数写数据给客户端之前的其他工作，TLS的加解密等等），你大可以本地写一个C/S服务来测试一下对性能的损耗。 2.随着流量的提高，规律会越来越明显。这个明显具体是什么?不要笼统地说时间会变长，要有可计算的公式才叫规律。事实上由于外部环境的复杂性（网络环境，服务器环境等）要得出这个规律并不简单，甚至是不可能的。

我只需要提出理论，我并没有说 一定怎样。理论物理学家没有义务证明，只需要提供理论。你要证明你可以证明。

我只是提出可能性。你可以通过实测证明或者证明为假命题。不要光“讨论证明”

“你大可以本地写一个C/S服务来测试一下对性能的损耗。”，你自己做。

“甚至是不可能的。” 请实测。

“要有可计算的公式才叫规律”，你说的很对。但是你把网络复杂性看作不可能的屏障，你让我如何回答呢？只要统计学上证明流量异常不就好了？

此issue将关闭。我不需要和任何人循环讨论特定话题。

**Comment by hahahrfool** [comment]
再次强调，我们可以看到，针对xtls漏洞的各种issue每一个都会 有人在 不实测的情况下 认为不成立。我是不关心的。只要不实测，就无法证明为假命题。

只要统计学上能区分出流量，即可。

前面我已经说了，如果短时间相邻探测能有0.5秒-1秒的差距，多次测试依然如此，比如正常访问延迟120ms，233 探测延迟总是600ms，即原延迟 delay_old + 500ms +- 误差，误差通过正常探测产生，墙才不管你流量问题，先封为敬。

**Comment by hahahrfool** [comment]
关于公式，可以自行学习概率论中的可信度计算

https://zhuanlan.zhihu.com/p/354217823

数据多了还可以机器学习，你能把神经网络得出的节点变成公式？自然不能，但是机器学习它就是被证明有用的。
